//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.CGSServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CGSServiceReference.CGS_ServerSoap")]
    public interface CGS_ServerSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Delivernum 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrackView", ReplyAction="*")]
        ConsoleApplication1.CGSServiceReference.TrackViewResponse TrackView(ConsoleApplication1.CGSServiceReference.TrackViewRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExpressQuery", ReplyAction="*")]
        ConsoleApplication1.CGSServiceReference.ExpressQueryResponse ExpressQuery(ConsoleApplication1.CGSServiceReference.ExpressQueryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrackViewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrackView", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.CGSServiceReference.TrackViewRequestBody Body;
        
        public TrackViewRequest() {
        }
        
        public TrackViewRequest(ConsoleApplication1.CGSServiceReference.TrackViewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TrackViewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Delivernum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusinessID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DataSign;
        
        public TrackViewRequestBody() {
        }
        
        public TrackViewRequestBody(string Delivernum, string BusinessID, string DataSign) {
            this.Delivernum = Delivernum;
            this.BusinessID = BusinessID;
            this.DataSign = DataSign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrackViewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrackViewResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.CGSServiceReference.TrackViewResponseBody Body;
        
        public TrackViewResponse() {
        }
        
        public TrackViewResponse(ConsoleApplication1.CGSServiceReference.TrackViewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TrackViewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TrackViewResult;
        
        public TrackViewResponseBody() {
        }
        
        public TrackViewResponseBody(string TrackViewResult) {
            this.TrackViewResult = TrackViewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExpressQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExpressQuery", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.CGSServiceReference.ExpressQueryRequestBody Body;
        
        public ExpressQueryRequest() {
        }
        
        public ExpressQueryRequest(ConsoleApplication1.CGSServiceReference.ExpressQueryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExpressQueryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeliverNum;
        
        public ExpressQueryRequestBody() {
        }
        
        public ExpressQueryRequestBody(string Token, string DeliverNum) {
            this.Token = Token;
            this.DeliverNum = DeliverNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExpressQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExpressQueryResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.CGSServiceReference.ExpressQueryResponseBody Body;
        
        public ExpressQueryResponse() {
        }
        
        public ExpressQueryResponse(ConsoleApplication1.CGSServiceReference.ExpressQueryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExpressQueryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExpressQueryResult;
        
        public ExpressQueryResponseBody() {
        }
        
        public ExpressQueryResponseBody(string ExpressQueryResult) {
            this.ExpressQueryResult = ExpressQueryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CGS_ServerSoapChannel : ConsoleApplication1.CGSServiceReference.CGS_ServerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CGS_ServerSoapClient : System.ServiceModel.ClientBase<ConsoleApplication1.CGSServiceReference.CGS_ServerSoap>, ConsoleApplication1.CGSServiceReference.CGS_ServerSoap {
        
        public CGS_ServerSoapClient() {
        }
        
        public CGS_ServerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CGS_ServerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CGS_ServerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CGS_ServerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.CGSServiceReference.TrackViewResponse ConsoleApplication1.CGSServiceReference.CGS_ServerSoap.TrackView(ConsoleApplication1.CGSServiceReference.TrackViewRequest request) {
            return base.Channel.TrackView(request);
        }
        
        public string TrackView(string Delivernum, string BusinessID, string DataSign) {
            ConsoleApplication1.CGSServiceReference.TrackViewRequest inValue = new ConsoleApplication1.CGSServiceReference.TrackViewRequest();
            inValue.Body = new ConsoleApplication1.CGSServiceReference.TrackViewRequestBody();
            inValue.Body.Delivernum = Delivernum;
            inValue.Body.BusinessID = BusinessID;
            inValue.Body.DataSign = DataSign;
            ConsoleApplication1.CGSServiceReference.TrackViewResponse retVal = ((ConsoleApplication1.CGSServiceReference.CGS_ServerSoap)(this)).TrackView(inValue);
            return retVal.Body.TrackViewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.CGSServiceReference.ExpressQueryResponse ConsoleApplication1.CGSServiceReference.CGS_ServerSoap.ExpressQuery(ConsoleApplication1.CGSServiceReference.ExpressQueryRequest request) {
            return base.Channel.ExpressQuery(request);
        }
        
        public string ExpressQuery(string Token, string DeliverNum) {
            ConsoleApplication1.CGSServiceReference.ExpressQueryRequest inValue = new ConsoleApplication1.CGSServiceReference.ExpressQueryRequest();
            inValue.Body = new ConsoleApplication1.CGSServiceReference.ExpressQueryRequestBody();
            inValue.Body.Token = Token;
            inValue.Body.DeliverNum = DeliverNum;
            ConsoleApplication1.CGSServiceReference.ExpressQueryResponse retVal = ((ConsoleApplication1.CGSServiceReference.CGS_ServerSoap)(this)).ExpressQuery(inValue);
            return retVal.Body.ExpressQueryResult;
        }
    }
}
