//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.WideBandService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WideBandService.WideBandDataServiceSoap")]
    public interface WideBandDataServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWideBandData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetWideBandData(string strToken, string strSystemId, string strPassword, System.DateTime reqTimeStamp, int strDataType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WideBandDataServiceSoapChannel : ConsoleApplication1.WideBandService.WideBandDataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WideBandDataServiceSoapClient : System.ServiceModel.ClientBase<ConsoleApplication1.WideBandService.WideBandDataServiceSoap>, ConsoleApplication1.WideBandService.WideBandDataServiceSoap {
        
        public WideBandDataServiceSoapClient() {
        }
        
        public WideBandDataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WideBandDataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WideBandDataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WideBandDataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetWideBandData(string strToken, string strSystemId, string strPassword, System.DateTime reqTimeStamp, int strDataType) {
            return base.Channel.GetWideBandData(strToken, strSystemId, strPassword, reqTimeStamp, strDataType);
        }
    }
}
